<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "geopicker"
 *
 * Auto generated by Extension Builder 2015-01-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'GeoPicker',
	'description' => 'BE extension that allows to handle GPS coordinate fields in your own extensions.',
	'category' => 'module',
	'author' => 'Marcus Biesioroff',
	'author_email' => 'marcus@biesioroff.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);